nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOWED_ORIGINS)%']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOWED_ORIGINS)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
